// <auto-generated />
using System;
using GridPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GridPulseDbContext))]
    [Migration("20251119155744_InitialOutages")]
    partial class InitialOutages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridPulse.Domain.Entities.Outage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("EstimatedRestoration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Reported");

                    b.HasKey("Id");

                    b.ToTable("outages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("17aa5a0f-4f5f-45ec-8dc0-1b53e876c111"),
                            Cause = "Tree on line",
                            EstimatedRestoration = new DateTimeOffset(new DateTime(2024, 10, 18, 18, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 10, 18, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReportedAt = new DateTimeOffset(new DateTime(2024, 10, 18, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceAddress = "123 Contoso Ave, Apex, NC",
                            ServiceLocationId = new Guid("f0b8c3a0-4f85-4f50-9b26-7b6b4c1cf001"),
                            Status = "CrewDispatched"
                        });
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.OutageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OutageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OutageId");

                    b.ToTable("outage_events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a4b46c-6e54-4d79-b3cb-9d537c8af901"),
                            CreatedBy = "system",
                            Message = "Outage acknowledged",
                            OutageId = new Guid("17aa5a0f-4f5f-45ec-8dc0-1b53e876c111"),
                            StatusFrom = 0,
                            StatusTo = 1,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 10, 18, 14, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "StatusChange"
                        });
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.OutageEvent", b =>
                {
                    b.HasOne("GridPulse.Domain.Entities.Outage", null)
                        .WithMany("Events")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Outage", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
