// <auto-generated />
using System;
using GridPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GridPulseDbContext))]
    [Migration("20251120161037_20251120_AddTicketsAndDispatch")]
    partial class _20251120_AddTicketsAndDispatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridPulse.Domain.Entities.AssignmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("TicketId");

                    b.ToTable("assignment_events", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentTicketCount")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceEndpoint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreferredShiftEnd")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_shift_end_minutes");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("Status");

                    b.ToTable("crews", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.CrewLocationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int>("SignalAgeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("SpeedMph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CrewId", "CapturedAt");

                    b.ToTable("crew_location_snapshots", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.DispatchRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("CompositeScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutoSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RecommendedRouteEtaMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreComponents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("TicketId", "CrewId", "CreatedAt");

                    b.ToTable("dispatch_recommendations", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Outage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("EstimatedRestoration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Reported");

                    b.HasKey("Id");

                    b.ToTable("outages", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.OutageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OutageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OutageId");

                    b.ToTable("outage_events", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedAssets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedCrewId")
                        .HasColumnType("uuid");

                    b.Property<int>("AuditVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("AutomationSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ingestion");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerImpact")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("EtaMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutageReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCrewId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.AssignmentEvent", b =>
                {
                    b.HasOne("GridPulse.Domain.Entities.Crew", "Crew")
                        .WithMany("Events")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GridPulse.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.CrewLocationSnapshot", b =>
                {
                    b.HasOne("GridPulse.Domain.Entities.Crew", "Crew")
                        .WithMany("LocationHistory")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.DispatchRecommendation", b =>
                {
                    b.HasOne("GridPulse.Domain.Entities.Crew", "Crew")
                        .WithMany("Recommendations")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridPulse.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Recommendations")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.OutageEvent", b =>
                {
                    b.HasOne("GridPulse.Domain.Entities.Outage", null)
                        .WithMany("Events")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Crew", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LocationHistory");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Outage", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GridPulse.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
